import type { Scenario, CallResult, MockSet } from './protocol.js';

export interface RecordedRun {
    scenario: Scenario;
    results: CallResult[];
    mockSet?: MockSet;
}

/** Escape a string for embedding in single-quoted JS. */
function q(s: string): string {
    return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

/** Pretty response body as a JS literal (parsed JSON if possible, else string). */
function bodyLiteral(body: string | undefined): string {
    if (!body) return 'undefined';
    try {
        return JSON.stringify(JSON.parse(body), null, 2);
    } catch {
        return q(body);
    }
}

/** Generate a Jest test for a Node/TS target. */
export function generateJestTest(run: RecordedRun): string {
    const { scenario, results, mockSet } = run;
    const lines: string[] = [];
    lines.push(`// Auto-generated by API Flow Test Debugger from run "${scenario.name}".`);
    lines.push(`// DB mode: ${scenario.dbMode}. Edit assertions as needed.`);
    lines.push('');

    if (mockSet && mockSet.boundaryMocks.length > 0) {
        lines.push('// Boundary mocks captured from the run:');
        for (const bm of mockSet.boundaryMocks) {
            lines.push(`//   ${bm.match} -> ${JSON.stringify(bm.returns)}`);
        }
        lines.push('');
    }

    lines.push(`describe(${q(scenario.name)}, () => {`);
    for (const rawCall of scenario.calls) {
        const res = results.find((r) => r.callId === rawCall.id);
        lines.push(`  it(${q(rawCall.name)}, async () => {`);
        lines.push(`    const res = await fetch(${q(rawCall.url)}, {`);
        lines.push(`      method: ${q(rawCall.method)},`);
        lines.push(`      headers: { 'Content-Type': 'application/json' },`);
        if (rawCall.method !== 'GET' && rawCall.body) {
            lines.push(`      body: JSON.stringify(${bodyLiteral(rawCall.body)}),`);
        }
        lines.push(`    });`);
        if (res && res.status != null) {
            lines.push(`    expect(res.status).toBe(${res.status});`);
        }
        if (res && res.responseBody) {
            lines.push(`    const body = await res.json();`);
            lines.push(`    expect(body).toEqual(${bodyLiteral(res.responseBody)});`);
        }
        lines.push('  });');
    }
    lines.push('});');
    lines.push('');
    return lines.join('\n');
}

/** Dispatch by language; only Jest/Node implemented so far. */
export function generateTest(run: RecordedRun): { filename: string; content: string } {
    const lang = run.mockSet?.language ?? 'node';
    switch (lang) {
        case 'node':
        default:
            return {
                filename: `${run.scenario.name.replace(/[^a-zA-Z0-9._-]/g, '-')}.flow.test.ts`,
                content: generateJestTest(run),
            };
    }
}
